### ISSUE TITLE
Multiple locations not working with separator ";"

### ISSUE THREAD

**Issue by Lisandro79** [rrwen/google_streetview#2]
Hi,

I have installed the library and I can download single images. I am working on Ubuntu 16.04, and I installed google_streetview via pip. When I run the command

` google_streetview --location=46.414382,10.013988;40.720032,-73.988354 `

I get my image in the 'downloads" folder. However, if I try with multiple locations:

` google_streetview --location=46.414382,10.013988;40.720032,-73.988354 `

Then I get this error:

```
[0] vPnURflnc8AZu5NMLYRddw
"==========================="
date: 2014-04
location: 
  lat: 46.4143421009
  lng: 10.0140059536
pano_id: vPnURflnc8AZu5NMLYRddw
status: OK
40.720032,-73.988354: command not found
```

Whenever I add a second argument to --location (as in this example) or to --headings, the program reports the second argument as a separate command.

Any ideas how to fix this?

Thanks a lot

Cheers

**Comment by rrwen** [comment]
Hi @Lisandro79 

Thank you for your detailed issue report.

Could you try the command again **with quotes** and see if it works?

```
google_streetview --location="46.414382,10.013988;40.720032,-73.988354" --heading="0;90;180;270"
```

**Comment by Lisandro79** [comment]
Hi @rrwen,

You are right, it works fine. Sorry for the post, I will try to get some more sleep before posting again.

Thanks a lot

Cheers

**Comment by rrwen** [comment]
@Lisandro79

No worries at all!
