### ISSUE TITLE
How to download 360 degree street view images?

### ISSUE THREAD

**Issue by Xunzhaocunzi** [rrwen/google_streetview#5]
Really appreciated your sharing with us.

I could only download one normal image, rather than 360 degree, pano image. Could you guide us how to download 360 degree images using the tool? 

Thank you

**Comment by rrwen** [comment]
Hi @Xunzhaocunzi

Please see:

https://rrwen.github.io/google_streetview/#image-search

and

https://rrwen.github.io/google_streetview/#multiple-arguments

You can adjust the field of vision `fov` and then rotate the camera `heading` accordingly.

For example, if the `fov` is 90, use increments of 90 for the `heading` until you cover 360 degrees:

```
google_streetview --location=46.414382,10.013988 --fov=90 --heading=0;90;180;270
```

**Comment by Xunzhaocunzi** [comment]
Thank you for the guide. I appreciated.
