### ISSUE TITLE
Getting multiple pictures in one request does not work (helpers.api_list)

### ISSUE THREAD

**Issue by TMorville** [rrwen/google_streetview#7]
## Purpose

I want to use the API to send a request to Google static street view API that contains several different lat/long coordinates, bearings, etc. 

## Example

Running the example in the documentation:

```
# Import google_streetview for the api and helper module
import google_streetview.api
import google_streetview.helpers

# Create a dictionary with multiple parameters separated by ;
apiargs = {
  'location': '46.414382,10.013988;40.720032,-73.988354',
  'size': '640x300;640x640',
  'heading': '0;90;180;270',
  'fov': '0;90;120',
  'pitch': '-90;0;90'
}

# Get a list of all possible queries from multiple parameters
api_list = google_streetview.helpers.api_list(apiargs)

# Create a results object for all possible queries
results = google_streetview.api.results(api_list)

# Preview results
results.preview()

# Download images to directory 'downloads'
results.download_links('downloads')

# Save metadata
results.save_metadata('metadata.json')
``` 
Simply produces a error: 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-396-9db778c1cdf8> in <module>
     19 
     20 # Preview results
---> 21 results.preview()
     22 
     23 # Download images to directory 'downloads'

~/.anaconda3/envs/ox/lib/python3.7/site-packages/google_streetview/api.py in preview(self, n, k, kheader)
    135 
    136       # (print_header) Print result header
--> 137       header = '\n[' + str(i) + '] ' + kv[kheader]
    138       print(header)
    139       print('=' * len(header))

KeyError: 'pano_id'

```

## Notes

The notes section provides any additional text that do not fit into the above sections.

**Comment by rrwen** [comment]
Hi @TMorville 

Thanks for notifying me of your issue!

Did you set up billing on Google API?

*If so, modify and try the code below:*

```python
results.preview(k=['date', 'status', 'location'], kheader = 'date')
```

*Let me know if it works and I can look into this.*

**Comment by ArdyBeheshti** [comment]
Hey @TMorville!

I am not sure if @rrwen has shown you the solution or if you have discovered your own answer but, this sample below is how I was able to pull multiple locations.

I will practice on importing a data set via SQL_db or csv files for a more streamlined process...

# Import modules
import google_streetview.api
import google_streetview.helpers

# Define parameters for street view api
location = '32.7420153,-117.1662487;32.7280124,-117.1709463'

apiargs = {
	'size': '600x300', # max 640x640 pixels
	'location': location,
	'heading': '151.78',
	'pitch': '-0.76',
	'key': '<API_KEY>'
}

# Get a list of all possible queries from multiple parameters
api_list = google_streetview.helpers.api_list(apiargs)

# Create a results object for all possible queries
results = google_streetview.api.results(api_list)

# Preview results
results.preview()

# Download images to directory 'downloads'
results.download_links('downloads')

# Save metadata
results.save_metadata('metadata.json')
